# Makefile for Amazon Challenges: Pool
# Daniel Mesham

all: Pool.java
	@printf "Compiling..."
	@javac Pool.java
	@printf "Done\n"

run: all
	@java Pool

clean:
	@printf "Removing class files..."
	@rm *.class
	@printf "Done\n"
